### PR TITLE
Add German language

### PR DESCRIPTION
**Pull request by emilengler**
I hope I've added it correctly.
I've added the german language.
I'm a native german so the translation should be fine.

### CODE REVIEW

**Comment by prasathmani** [comment]
file size keep increasing due to languages, so I'm thinking into different approach.

**Comment by emilengler** [comment]
You could put them into JSON files

**Comment by simon511000** [comment]
> You could put them into JSON files

Yes but the goal of tinymanager is to have a single file

**Comment by emilengler** [comment]
I mean optional translation files that the user can download if he want as an example:
`if(file_exists("translation.json") {
// Stuff to import the json file
}
else {
// Use english
}`

**Pull request merged**
