### PR TITLE
Add Docker

### PR DESCRIPTION
**Pull request by babeuloula**
Allow to use tinyfilemanager through a docker container with PHP 7.4

### CODE REVIEW

**Comment by wangerzi** [comment]
@babeuloula @prasathmani Hi, man

I like this project and I write a new Dockerfile for this, beacause after **I built the Dockerfile in this commit, I can't preview my file in my website** .

I found the answer about this question at there: [PHP: Built-in web server](https://www.php.net/manual/en/features.commandline.webserver.php)

So, I rename the `tinyfilemanager.php` to `index.php` in my Dockerfile and serve at `/var/www/html`. If you modify `$root_path` and `$root_url` in `config.php`, it will be better.

I'm already publish a docker image in the DockerHub [https://hub.docker.com/r/wj2015/tinyfilemanager](https://hub.docker.com/r/wj2015/tinyfilemanager)
So we can use it by runing this following command (Only arm7l now, but you can built more image by the same file for other platform)

```shell
docker run -v /var/youpath/:/var/www/html/data -p 8080:80 -d --restart=always wj2015/tinyfilemanager:armv7l
```

Config examples: 
```php
// .....................
// Root path for file manager
// use absolute path of directory i.e: '/var/www/folder' or $_SERVER['DOCUMENT_ROOT'].'/folder'
$root_path = $_SERVER['DOCUMENT_ROOT'].'/data';
// .....................
// Root url for links in file manager.Relative to $http_host. Variants: '', 'path/to/subfolder'
// Will not working if $root_path will be outside of server document root
$root_url = 'data/';
// .....................
```

Put Dockerfile to the project source path, and run `docker build . -t yourname/tinyfilemanager:tag` for yourself.
```Dockerfile
FROM php:7.4-cli-alpine

# if run in China
# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN apk add \
    libzip-dev \
    oniguruma-dev

RUN docker-php-ext-install \
    zip \
    mbstring \
    iconv \
    fileinfo

COPY . /var/www/html

WORKDIR /var/www/html

COPY tinyfilemanager.php index.php

CMD ["sh", "-c", "php -S 0.0.0.0:80"]
```

**Comment by jeffrey-lunaon** [comment]
@prasathmani New update: support amd64 🍺

You should check your system plaform by `uname -a`, and choose a correct tag to run.

| Platform | Tag   | Devices              |
| -------- | ----- | -------------------- |
| armv7    | armv7 | raspberry            |
| amd64    | amd64 | Linux Server / Macos |

I built this image beacause I have to run it on my raspbery, if you run it at **armv7** platform (raspberry, etc.), you can use this:

```shell
docker run -v /var/youpath/:/var/www/html/data -p 8080:80 -d --restart=always wj2015/tinyfilemanager:armv7l
```

Or you can run **amd64** at MacOs or Linux Server.

```shell
docker run -v /var/youpath/:/var/www/html/data -p 8080:80 -d --restart=always wj2015/tinyfilemanager:amd64
```

```
>  Notice: Your path need be absolute path, and it will be served by tinyfilemanager.
```

And then, you can access http://ip:8080, enjoy it!

**Comment by RobinJ1995** [comment]
It'd be nice if this were to be merged and maybe automatically published to Dockerhub :)

**Comment by DaAwesomeP** [comment]
Any updates? If there is anything blocking (i.e. Docker publish pipeline) please let us know!

**Comment by prasathmani** [comment]
@wangerzi , can you share some documentation links, how to publish docker. so I can try it.

**Comment by wangerzi** [comment]
> @wangerzi , can you share some documentation links, how to publish docker. so I can try it.

OK, I think you can do this following steps

## Register DockerHub account for project

Register for a docker id at [DockerHub](https://hub.docker.com/)

Help link: https://docs.docker.com/docker-id/

### Create repository for this project

Log In and click 「Create Repository」and full in the information.

image

## [manual] manual build and manual push

### Checkout and build docker image

checkout to correct version

```shell
git checkout v2.4.3
```

Copy Dockerfile to project path

```Dockerfile
FROM php:7.4-cli-alpine

# if run in China
# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN apk add \
    libzip-dev \
    oniguruma-dev

RUN docker-php-ext-install \
    zip \
    mbstring \
    iconv \
    fileinfo

COPY . /var/www/html

WORKDIR /var/www/html

COPY tinyfilemanager.php index.php

CMD ["sh", "-c", "php -S 0.0.0.0:80"]
```

Execute this command 

```shell
docker login
# .....input your docker id and password
docker build . -t prasathmani/tinyfilemanager:v2.4.3
docker push prasathmani/tinyfilemanager:v2.4.3
```

### How to use this docker



## [Advanced] auto build docker image when you update the project.

### DockerHub Automated Builds

Unlucky, this function need to pay, but it's easy to use, you don't need add any code for this, when you have a new commit, DockerHub will help you build and publish.

image


### GithubActions

You can find a lots of actions in GithubActions, you can copy and modify some config to build and push docker image when you publish a new version.


Refer: https://github.com/marketplace/actions/build-and-push-docker-images#tag_with_ref

Examples:

> this config means when you push some commit at `master`, trigger the jobs what you defined, `step 3` and `step 4`, you should defined your docker id and password at 「Secrets」
image


```yaml
name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
```

## Add some document at README.md

Introduce for 
- how to use
- put your docker link

**Comment by wangerzi** [comment]
I don't finish it at above, because I was interrupted by a company meeting. And I want to modify some code for build docker, maybe tonight, I will make a new PR to build docker image automatic and add some instruction in `README.md`, and if you accept it @prasathmani you can only need register at Docker Hub and add secret at github.🤓

**Comment by prasathmani** [comment]
@wangerzi  thank you so much for your quick response, i'll check the documentation

**Comment by wangerzi** [comment]
> @wangerzi thank you so much for your quick response, i'll check the documentation

I created a new PR at https://github.com/prasathmani/tinyfilemanager/pull/619

**Pull request closed without merging**
