### PR TITLE
feat: add Dockerfile and auto publish.

### PR DESCRIPTION
**Pull request by wangerzi**
Hi, @prasathmani , I'm already build and test manual build and GithubAction auto build for this. ❤❤❤

I suggest you can merge this code by this following steps:

- Create your DockerHub account, and generate an AccessToken at first.
image

- Then add this following secrets in github setting

image

- Merge the code and publish a new version
image

- Push Success and check DockerHub
image

- Test docker image with command

Make sure you have **already installed docker**, [Install reference](https://docs.docker.com/engine/install/)

> **Notice:** Your need an absolute path, and it will be served by tinyfilemanager.
> 
> If you want to serve this project at **raspberry pi or another special platform**, you can download project and **build image by yourself**.
You can execute this following commands:

```shell
$ docker run -d -v /absolute/path:/var/www/html/data -p 80:80 --restart=always --name tinyfilemanager prasathmani/tinyfilemanager:master
$ docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED         STATUS         PORTS                                       NAMES
648dfba9c0ff   prasathmani/tinyfilemanager:master   "docker-php-entrypoi…"   4 minutes ago   Up 4 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp           tinyfilemanager
```
Access `http://127.0.0.1/` and enter default username and password, then enjoy it.

image

### CODE REVIEW

**Comment by prasathmani** [comment]
I have completed all the steps, just want to check `config-docker-sample.php` file is required?

**Comment by wangerzi** [comment]
> I have completed all the steps, just want to check `config-docker-sample.php` file is required?

I modify the `config-docker-sample.php` because docker volume `-v /source/path:/dist/path` will cover all the file, if I don't change `$root_path` and `$root_url` to a sub directory, `index.php` will be covered and can't be run or we must serve the data directory in sub path. So, if we have a better way to solve this problem, I can change the dockerfile and remove `config-docker-sample.php`.

```php
// Root path for file manager
// use absolute path of directory i.e: '/var/www/folder' or $_SERVER['DOCUMENT_ROOT'].'/folder'
$root_path = $_SERVER['DOCUMENT_ROOT'].'/data';

// Root url for links in file manager.Relative to $http_host. Variants: '', 'path/to/subfolder'
// Will not working if $root_path will be outside of server document root
$root_url = 'data/';
```

**Comment by wangerzi** [comment]
Hey, @prasathmani  I have a new idea for this, how about change the `config.php` automatic when I build the image by sed command or another way, then you can maintain only `config-sample.php`, but I should write more document to describe this section. Is it ok?

**Comment by prasathmani** [comment]
> Hey, @prasathmani I have a new idea for this, how about change the `config.php` automatic when I build the image by sed command or another way, then you can maintain only `config-sample.php`, but I should write more document to describe this section. Is it ok?

yes, I thing it is a good idea.

**Comment by wangerzi** [comment]
@prasathmani Hi, I'm already complete the document and updated Dockerfile. Do we have another details need to modify?✔

**Review by prasathmani — APPROVED** [review]

**Comment by prasathmani** [comment]
@wangerzi ,thank for your support, code merged, docker url is https://hub.docker.com/r/tinyfilemanager/tinyfilemanager, do I need to update  anything ?

**Comment by wangerzi** [comment]
> @wangerzi ,thank for your support, code merged, docker url is https://hub.docker.com/r/tinyfilemanager/tinyfilemanager, do I need to update anything ?

👍👍👍, wonderful, I test the newest docker again, it works well!

But I guess you will register a DockerHub account named `prasathmani` before, so the`README.md` document what I wrote and some code comment in `Dockerfile`, I totally using `prasathmani/tinyfilemanager`, you should global replace `prasathmani/tinyfilemanager` to `tinyfilemanager/tinyfilemanager`, otherwise users will got an error like `docker: Error response from daemon: pull access denied for prasathmani/tinyfilemanager, repository does not exist`.

**Comment by prasathmani** [comment]
@wangerzi  thanks for the update, if possible can you create a PR to update docker file

**Pull request merged**
