### PR TITLE
Check file extension on rename and creation

### PR DESCRIPTION
**Pull request by CodeFetch**
The allowed file extensions was only checked on upload.
Thus it is possible to upload a file with a permitted extension and change it to a non-permitted one afterwards.
That renders the „allowed upload file extension“ feature useless.
This commit checks the file extension on file rename and creation attempts, too.

Actually I think this should be reworked completely (I don't have time for that).
Allowed file extensions should be configurable each for:
- Directory listing extensions
- Read extensions
- Edit extensions
- Upload/creation/rename extensions

### CODE REVIEW

**Comment by VincentVandalon** [comment]
Well spotted, looks like a worthwhile addition and clean code.

**Comment by prasathmani** [comment]
This feature is available now in the application, so closing the PR.

**Comment by CodeFetch** [comment]
@prasathmani The interesting thing to me is that it seems you did not understand the purpose of Github. You could just have merged my PR, but instead you did double-work and "threw my work into the bin". I'm not going to use or work on this piece of software ever again... Very disappointing.

**Comment by prasathmani** [comment]
@CodeFetch, I am really very sorry for the inconvenience, I know that you spend time to understand the code and add the feature, really appreciate your time and efforts. Due to time constraints, I didn’t merge that time when you created PR, after some time got code conflicts, so I didn't merged many PR’s. Hereafter I try to check and merge the PR regularly. I hope you continue to use this application. Thanks again.

**Pull request closed without merging**
