### PR TITLE
Dynamic Browser Tab Title Handling Based on File Context

### PR DESCRIPTION
**Pull request by jabedbd**
Now it will show the filename as the browser tab title so that the user can easily identify which file is opened on which tab.

### CODE REVIEW

**Review by ner00 — CHANGES_REQUESTED** [review]
For the sake of simplicity, I propose to remove lines 3722 and 3734, then replace line 3733 with:
```php
    echo isset($_GET['edit']) ? $_GET['edit'] : fm_enc(APP_TITLE);
```

**Comment by jabedbd** [comment]
> For the sake of simplicity, I propose to remove lines 3722 and 3734, then replace line 3733 with:
> 
> ```
>     echo isset($_GET['edit']) ? $_GET['edit'] : fm_enc(APP_TITLE);
> ```

Updated

**Comment by jabedbd** [comment]
> @jabedbd It's still pending the commented review.

Hi, is there anything I can do from my side? i have already updated the code that you mentioned above.

**Comment by jabedbd** [comment]
> > > @jabedbd It's still pending the commented review.
> > 
> > 
> > Hi, is there anything I can do from my side? i have already updated the code that you mentioned above.
> 
> I think so, yes. Remove the trailing space in line 3721, after `'navbar-normal';`, that was you who added that space, it did not exist before and doesn't need to be there anyway.

Done. The extra trailing space is removed

**Review by ner00 — APPROVED** [review]
LGTM

**Review by prasathmani — APPROVED** [review]

**Pull request merged**
