### PR TITLE
Chunked file upload

### PR DESCRIPTION
**Pull request by mythsmith**
Removes any PHP or server-side file-upload limits by using file chunks.

Cheap shared hosting services usually does not allow to change file upload settings, to save resources. By allowing Dropzone chunked file upload feature, unlimited size files can be uploaded.

### CODE REVIEW

**Comment by prasathmani** [comment]
I will validate and merge the code

**Comment by mythsmith** [comment]
Thanks @prasathmani . I made the changes in a hurry, and I realize they are very little documented. I can further document them if you wish. Also, the chunked behaviour could be configured as option, and offer further tweaks (chunksize, maximum file upload, etc).

**Comment by kofbox** [comment]
@prasathmani Good day. I would like to add that this option will be extremely useful for everyone who uses CloudFlare services for their sites, even if they use "not cheap hosting", since CloudFlare sets chunk size for the minimum tariff plan "Free" - 100 Mb, and for the maximum tariff plan - 500 Mb.

**Review by prasathmani — APPROVED** [review]

**Comment by ramok** [comment]
```        if(file_exists ($fullPath) && !$override_file_name && !$chunks) {
```
there is only place where variable `chunks` used
```... PHP Notice:  Undefined variable: chunks ...tinyfilemanager/tinyfilemanager.php on line 951```

**Comment by ner00** [comment]
Yes, very strange. I wonder if the variable `$chunks` was ever used before, as it stands it doesn't serve any purpose.

**Comment by ner00** [comment]
This was fixed after issue https://github.com/prasathmani/tinyfilemanager/issues/1025 and merged PR https://github.com/prasathmani/tinyfilemanager/pull/1026

**Pull request merged**
